# ==============================
# COMMON SETUP
# ==============================
# Travis only runs on:
# Commit to "continuous" branch.
# Valid semver tag is created.
# ==============================
language: node_js

node_js:
  - '8'

env:
  global:
    # Versions
    - NPM_VERSION="6.0.1"
    # Directories
    - RB_COMPONENT_DIR="$TRAVIS_BUILD_DIR"
    - RB_REPO_NAME="$TRAVIS_REPO_SLUG"
    # TOKENS (in order): TRAVIS_TOKEN, NPM_TOKEN

cache:
  directories:
    - node_modules     # repo root node_modules
    - "$(npm root -g)" # global node_modules directory
    - "$(npm bin -g)/rapid-build"

# Install Global Dependencies
# ===========================
before_install:
  - echo $RB_COMPONENT_DIR
  - echo $TRAVIS_TOKEN
  - echo $RB_REPO_NAME
  - if [[ $(npm -v) != $NPM_VERSION ]]; then npm install -g npm@${NPM_VERSION}; fi # version check
  - if [[ -z $(command -v rapid-build) ]]; then npm install -g rapid-build@5; fi   # if not installed
